### =======================================
###  ROTAS PÚBLICAS
### =======================================

### Listar todos os Projetos
GET http://localhost:5000/projects

### Enviar Mensagem de Contato
POST http://localhost:5000/contact
Content-Type: application/json

{
    "name": "Visitante Teste",
    "email": "visitante@teste.com",
    "message": "Olá, gostei do seu portfólio!"
}


### =======================================
###  ROTAS DE AUTENTICAÇÃO
### =======================================

### Registrar um novo usuário (ADMIN)
# RODE ISSO APENAS SE PRECISAR CRIAR UM NOVO USUÁRIO
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "email": "gui_bisof@hotmail.com",
    "password": "43010609Guilherme@@"
}

### Fazer Login
# Use esta rota para pegar seu token de acesso
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "gui_bisof@hotmail.com",
  "password": "43010609Guilherme@@"
}


### =======================================
###  ROTAS PROTEGIDAS (PRECISAM DE TOKEN)
### =======================================

### Criar um novo projeto (COM AUTENTICAÇÃO)
POST http://localhost:5000/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZ3VpX2Jpc29mQGhvdG1haWwuY29tIiwiaWF0IjoxNzQ5MTQ4MjMxLCJleHAiOjE3NDkxNzcwMzF9.34i2aQaAR6Q08Y98aKa5kxPmo2uMpFbm7GJB0SCL6oA

{
  "title": "Meu Primeiro Projeto Autenticado",
  "description": "Este projeto só pode ser criado com um token válido.",
  "imageUrl": "",
  "repoUrl": ""
}